language: node_js
node_js:
- '6'
script: npm run ci
env:
  global:
  - secure: "AsKT1Jdh0JFB0iWMY8NIfdqSohXRCK2qGrbjWbkLiPA9ueifNyI1Sn5SWDua6uSGuVsF2OX+XtFYMVhGOobtiC3N+bYdBX1UD2jPrNKzBIXvlsW2D/oc03HcNW4hSNVb09wS+It9eMcnplIw6dX3Q7TPhhGLrXg9ModLe74fNlI="
  - secure: "evomBAnDPb3bk2DmUjLMuIeevLPHa/vCadPDQIhCMIR6WNpTBCCkiBFU0185JpDgzZ4dq7a5KWiKQORzqUbgKoRm8cXa6N7x1k55NG+DOuZSNfSJfTN1BWIQGFahCDsq/qvdFI5g49wuT4Qyp7ErQ8/dYokg4LCXpnsf+glF6VI="
